project.name=intyg

artifact.name=intyg-mock-service
artifact.version=0.5.0.3

git.url=https://github.com/sklintyg/intyg-mock-service.git
git.branch=main

builder.image=app-builder-image
builder.image.tag=21.0.6

runtime.image=springboot-base
runtime.image.tag=21.0.2

build.args=build qualityGate
build.cache.args=build
sonarqube.args=