### GET register certificate
GET http://localhost:18888/api/register-certificate

### GET register certificate as xml
GET http://localhost:18888/api/register-certificate/88cc03c8-9099-4c2e-a8e2-3accae213484/xml

### DELETE all register certificate
DELETE http://localhost:18888/api/register-certificate