app.repository.register-certificate.max-size=1000
app.repository.revoke-certificate.max-size=1000
app.repository.send-message-to-recipient.max-size=1000
app.repository.certificate-status-update-for-care.max-size=1000
app.repository.store-log.max-size=1000
logging.structured.format.console=ecs
spring.application.name=intyg-mock-service
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.enabled=true
