app:
  passthrough:
    mtls:
      certificate-file:
      certificate-password:
      certificate-type: PKCS12
      key-manager-password:
      truststore-file:
      truststore-password:
      truststore-type: JKS
    certificate-status-update-for-care:
      enabled: false
      url:
    register-certificate:
      enabled: false
      url:
    revoke-certificate:
      enabled: false
      url:
    send-message-to-recipient:
      enabled: false
      url:
    store-log:
      enabled: false
      url:
  repository:
    certificate-status-update-for-care:
      max-size: 1000
    register-certificate:
      max-size: 1000
    revoke-certificate:
      max-size: 1000
    send-message-to-recipient:
      max-size: 1000
    store-log:
      max-size: 1000

spring:
  application:
    name: intyg-mock-service

logging:
  structured:
    format:
      console: ecs

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
    tags-sorter: alpha
